print("HTTP/1.1 OK 200\r\n", end="")
print("Content-Type: text/html\r\n", end="")
print("Content-Length: 483\r\n\r\n", end="")
print('<!DOCTYPE html>')
print('<html>')
print('	<head>')
print('		<title>cgi_hello_python</title>')
print('		<style>')
print('			html { color-scheme: light dark; }')
print('			body { width: 35em; margin: 0 auto; font-family: Tahoma, Verdana, Arial, sans-serif; }')
print('		</style>')
print('	</head>')
print('	<body>')
print('		<center>')
print('			<h1>Webserv :: Hello!</h1>')
print('			<img src="https://media.tenor.com/nB1fpcfcaKkAAAAC/hh.gif" alt="hello cat meme" style="width: 80%">')
print('			<hr>')
print('			<h2>- you success run CGI webserv with -<br>- python -</h2>')
print('		</center>')
print('	</body>')
print('</html>')