#!/bin/bash
content="HTTP/1.1 200 OK\r\n"
content+="Content-Type: text/html\r\n"
content+="Content-Length: 497\r\n\r\n"
content+="<!DOCTYPE html>\n"
content+="<html>\n"
content+="	<head>\n"
content+="		<title>cgi_bye_bashScript</title>\n"
content+="		<style>\n"
content+="			html { color-scheme: light dark; }\n"
content+="			body { width: 35em; margin: 0 auto; font-family: Tahoma, Verdana, Arial, sans-serif; }\n"
content+="		</style>\n"
content+="	</head>\n"
content+="	<body>\n"
content+="		<center>\n"
content+="			<h1>Webserv :: Goodbye!</h1>\n"
content+="			<hr>\n"
content+='			<img src="https://media.tenor.com/Xl-paI3WxIAAAAAC/good-bye-simpsons.gif" alt="goodbye" style="width: 80%">'
content+="\n			<hr>\n"
content+="			<h2>- you success run CGI webserv with -<br>- bashscript -</h2>"
content+="		</center>\n"
content+="	</body>\n"
content+="</html>\n"
echo -e $content;